"""Game Progress catalog: NCS-derived missions, challenges and map locations.

Generated by the update pipeline:

- ``core/data/progress_catalog.json`` (``export-progress-catalog``): missions
  and objectives, mission sets, challenges and the in-game challenge menu,
  discovery locations with world coordinates, regions and echo logs;
- ``assets/progress_maps/maps.json`` (``export-progress-maps``): map artwork,
  discovery icons and one linear world->texture projection per map.

All ids are lowercase to match save keys. Localized text is stored as
``{"en": ..., "zh": ..., "ru": ...}``; the game ships no Ukrainian text, so
Ukrainian falls back to English.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any

from . import resource_loader

CATALOG_PATH = "core/data/progress_catalog.json"
MAPS_DIR = "assets/progress_maps"
_LANGUAGE_KEYS = {"zh-CN": "zh", "en-US": "en", "ru": "ru", "ua": "en"}


@lru_cache(maxsize=1)
def catalog() -> dict[str, Any]:
    return resource_loader.load_json_resource(CATALOG_PATH) or {}


@lru_cache(maxsize=1)
def maps() -> dict[str, Any]:
    return resource_loader.load_json_resource(f"{MAPS_DIR}/maps.json") or {}


def available() -> bool:
    return bool(catalog().get("missions"))


def language_key(lang: str) -> str:
    return _LANGUAGE_KEYS.get(str(lang), "en")


def text(value: Any, lang: str, fallback: str = "") -> str:
    """Pick the localized string for ``lang`` (then English, then anything)."""
    if not isinstance(value, dict) or not value:
        return fallback
    key = language_key(lang)
    return str(value.get(key) or value.get("en") or next(iter(value.values()), "") or fallback)


def section(name: str) -> dict[str, Any]:
    data = catalog().get(name)
    return data if isinstance(data, dict) else {}


def region_title(region: str, lang: str) -> str:
    row = section("regions").get(str(region).lower()) or {}
    return text(row.get("title"), lang, str(region))


def map_info(world: str) -> dict[str, Any]:
    return (maps().get("maps") or {}).get(world) or {}


def map_image_path(world: str) -> Path | None:
    image = map_info(world).get("image")
    path = resource_loader.get_resource_path(f"{MAPS_DIR}/{image}") if image else None
    return path if path and path.exists() else None


def icon_path(asset: str) -> Path | None:
    """Local PNG for a discovery icon asset path (``/Game/.../ico_x.ico_x``)."""
    stem = str(asset or "").split(".", 1)[0].rsplit("/", 1)[-1].lower()
    relative = (maps().get("icons") or {}).get(stem)
    path = resource_loader.get_resource_path(f"{MAPS_DIR}/{relative}") if relative else None
    return path if path and path.exists() else None


def project(world: str, x: float, y: float) -> tuple[float, float] | None:
    """World centimetres -> normalised texture UV, or None when off the map."""
    transform = map_info(world).get("transform")
    if not transform or len(transform) != 4:
        return None
    kx, cx, ky, cy = transform
    u, v = kx * float(x) + cx, ky * float(y) + cy
    if 0.0 <= u < 1.0 and 0.0 <= v < 1.0:
        return u, v
    return None
