# This file is automatically generated. Do not edit.

def _mirror_bits(n, bit_count):
    re = 0
    for i in range(bit_count):
        if (n >> i) & 1:
            re |= 1 << ((bit_count - 1) - i)
    return re

UINT2_MIRROR = tuple(_mirror_bits(i, 2) for i in range(1 << 2))
UINT3_MIRROR = tuple(_mirror_bits(i, 3) for i in range(1 << 3))
UINT4_MIRROR = tuple(_mirror_bits(i, 4) for i in range(1 << 4))
UINT5_MIRROR = tuple(_mirror_bits(i, 5) for i in range(1 << 5))
UINT7_MIRROR = tuple(_mirror_bits(i, 7) for i in range(1 << 7))
UINT8_MIRROR = tuple(_mirror_bits(i, 8) for i in range(1 << 8))
UINT11_MIRROR = tuple(_mirror_bits(i, 11) for i in range(1 << 11))
